using System.IO;

namespace PhotoViewer.Wpf;

/// <summary>
/// A capability for one WPF-owned metadata cache. Product callers may select
/// the configured cache directory, but the leaf is always the SHA-256 catalog
/// identity generated by the application. Direct string fixtures are accepted
/// only below the OS TEMP directory.
/// </summary>
internal sealed class MetadataIndexStorePath
{
    private const string SqliteExtension = ".sqlite3";

    private MetadataIndexStorePath(string fullPath)
    {
        FullPath = fullPath;
        DirectoryPath = Path.GetDirectoryName(fullPath)
            ?? throw new InvalidDataException(
                "The metadata cache path did not have a directory.");
    }

    internal string FullPath { get; }
    internal string DirectoryPath { get; }
    internal string LegacyPath => Path.ChangeExtension(FullPath, ".pvmi");

    internal static MetadataIndexStorePath ForCatalogIdentity(
        string directory,
        string catalogDigest)
    {
        string fullDirectory = Path.TrimEndingDirectorySeparator(
            Path.GetFullPath(directory));
        if (!IsLowerHexSha256(catalogDigest))
        {
            throw new InvalidDataException(
                "The metadata cache catalog identity was not a SHA-256 digest.");
        }

        string fileName = catalogDigest + SqliteExtension;
        string candidate = Path.GetFullPath(
            Path.Combine(fullDirectory, fileName));
        if (!string.Equals(
                Path.GetDirectoryName(candidate),
                fullDirectory,
                StringComparison.OrdinalIgnoreCase)
            || !string.Equals(
                Path.GetFileName(candidate),
                fileName,
                StringComparison.Ordinal))
        {
            throw new InvalidDataException(
                "The metadata cache path escaped its configured directory.");
        }

        return new MetadataIndexStorePath(candidate);
    }

    internal static MetadataIndexStorePath ForManagedTempFixture(string path)
    {
        string fullPath = Path.GetFullPath(path);
        if (!Path.IsPathFullyQualified(path)
            || !string.Equals(
                Path.GetExtension(fullPath),
                SqliteExtension,
                StringComparison.OrdinalIgnoreCase)
            || !IsStrictTempDescendant(fullPath))
        {
            throw new InvalidDataException(
                "Synthetic metadata cache fixtures must be SQLite files below TEMP.");
        }

        return new MetadataIndexStorePath(fullPath);
    }

    internal static bool AcceptsManagedTempFixtureForSmoke(string path)
    {
        try
        {
            _ = ForManagedTempFixture(path);
            return true;
        }
        catch (Exception ex) when (ex is InvalidDataException
            or ArgumentException
            or NotSupportedException
            or IOException
            or UnauthorizedAccessException)
        {
            return false;
        }
    }

    private static bool IsLowerHexSha256(string value)
        => value.Length == 64
            && value.All(static character => character is >= '0' and <= '9'
                or >= 'a' and <= 'f');

    private static bool IsStrictTempDescendant(string path)
    {
        string tempRoot = Path.TrimEndingDirectorySeparator(
            Path.GetFullPath(Path.GetTempPath()));
        string fullPath = Path.GetFullPath(path);
        string relative = Path.GetRelativePath(tempRoot, fullPath);
        bool lexicalInside = !Path.IsPathFullyQualified(relative)
            && relative is not ("." or "..")
            && !relative.StartsWith(
                ".." + Path.DirectorySeparatorChar,
                StringComparison.Ordinal)
            && !relative.StartsWith(
                ".." + Path.AltDirectorySeparatorChar,
                StringComparison.Ordinal);
        if (!lexicalInside)
            return false;

        string? directory = Path.GetDirectoryName(fullPath);
        // This is the validation boundary itself. The synthetic parent and
        // TEMP root must already exist so their final handle identities can be
        // compared before the capability is issued.
        // codeql[cs/path-injection]
        if (string.IsNullOrWhiteSpace(directory)
            || !Directory.Exists(directory)
            || !WindowsPathIdentity.TryResolveExistingDirectory(
                tempRoot,
                out string canonicalTempRoot)
            || !WindowsPathIdentity.TryResolveExistingDirectory(
                directory,
                out string canonicalDirectory))
        {
            return false;
        }

        string canonicalPrefix = Path.TrimEndingDirectorySeparator(
                canonicalTempRoot)
            + Path.DirectorySeparatorChar;
        return canonicalDirectory.StartsWith(
            canonicalPrefix,
            StringComparison.OrdinalIgnoreCase);
    }
}
