using System.IO;

namespace PhotoViewer.Wpf;

/// <summary>
/// A capability for one WPF-owned metadata cache. Product callers may select
/// only the fixed LocalApplicationData product tree. The leaf is always the
/// SHA-256 catalog identity generated by the application. Synthetic directory
/// overrides and direct string fixtures are accepted only below OS TEMP.
/// </summary>
internal sealed class MetadataIndexStorePath
{
    private const string ApplicationDirectoryName = "PhotoViewer.Wpf";
    private const string MetadataDirectoryName = "metadata-index-v1";
    private const string SqliteExtension = ".sqlite3";

    private MetadataIndexStorePath(string fullPath)
    {
        FullPath = fullPath;
        DirectoryPath = Path.GetDirectoryName(fullPath)
            ?? throw new InvalidDataException(
                "The metadata cache path did not have a directory.");
    }

    internal string FullPath { get; }
    internal string DirectoryPath { get; }
    internal string LegacyPath => Path.ChangeExtension(FullPath, ".pvmi");

    internal static MetadataIndexStorePath ForCurrentUserCatalogIdentity(
        string catalogDigest)
    {
        string root = Environment.GetFolderPath(
            Environment.SpecialFolder.LocalApplicationData);
        if (string.IsNullOrWhiteSpace(root)
            || !Path.IsPathFullyQualified(root))
        {
            throw new InvalidDataException(
                "The metadata cache root was not an absolute OS path.");
        }

        string fullRoot = Path.TrimEndingDirectorySeparator(
            Path.GetFullPath(root));
        string applicationDirectory = FixedChild(
            fullRoot,
            ApplicationDirectoryName);
        string metadataDirectory = FixedChild(
            applicationDirectory,
            MetadataDirectoryName);
        return ForCatalogIdentityInDirectory(
            metadataDirectory,
            catalogDigest);
    }

    internal static MetadataIndexStorePath ForManagedTempCatalogIdentity(
        string directory,
        string catalogDigest)
    {
        if (!TryResolveManagedTempDirectory(
                directory,
                out string canonicalDirectory))
        {
            throw new InvalidDataException(
                "Synthetic metadata cache directories must have a trusted parent below TEMP.");
        }

        return ForCatalogIdentityInDirectory(
            canonicalDirectory,
            catalogDigest);
    }

    private static MetadataIndexStorePath ForCatalogIdentityInDirectory(
        string directory,
        string catalogDigest)
    {
        string fullDirectory = Path.TrimEndingDirectorySeparator(
            Path.GetFullPath(directory));
        if (!IsLowerHexSha256(catalogDigest))
        {
            throw new InvalidDataException(
                "The metadata cache catalog identity was not a SHA-256 digest.");
        }

        string fileName = catalogDigest + SqliteExtension;
        string candidate = Path.GetFullPath(
            Path.Combine(fullDirectory, fileName));
        if (!string.Equals(
                Path.GetDirectoryName(candidate),
                fullDirectory,
                StringComparison.OrdinalIgnoreCase)
            || !string.Equals(
                Path.GetFileName(candidate),
                fileName,
                StringComparison.Ordinal))
        {
            throw new InvalidDataException(
                "The metadata cache path escaped its configured directory.");
        }

        return new MetadataIndexStorePath(candidate);
    }

    internal static MetadataIndexStorePath ForManagedTempFixture(string path)
    {
        string fullPath = Path.GetFullPath(path);
        string? directory = Path.GetDirectoryName(fullPath);
        if (!Path.IsPathFullyQualified(path)
            || !string.Equals(
                Path.GetExtension(fullPath),
                SqliteExtension,
                StringComparison.OrdinalIgnoreCase)
            || string.IsNullOrWhiteSpace(directory)
            || !TryResolveManagedTempDirectory(
                directory,
                out string canonicalDirectory))
        {
            throw new InvalidDataException(
                "Synthetic metadata cache fixtures must be SQLite files below TEMP.");
        }

        return new MetadataIndexStorePath(
            FixedChild(canonicalDirectory, Path.GetFileName(fullPath)));
    }

    internal static bool AcceptsManagedTempFixtureForSmoke(string path)
    {
        try
        {
            _ = ForManagedTempFixture(path);
            return true;
        }
        catch (Exception ex) when (ex is InvalidDataException
            or ArgumentException
            or NotSupportedException
            or IOException
            or UnauthorizedAccessException)
        {
            return false;
        }
    }

    internal static bool AcceptsManagedTempCatalogDirectoryForSmoke(
        string directory,
        string catalogDigest)
    {
        try
        {
            _ = ForManagedTempCatalogIdentity(directory, catalogDigest);
            return true;
        }
        catch (Exception ex) when (ex is InvalidDataException
            or ArgumentException
            or NotSupportedException
            or IOException
            or UnauthorizedAccessException)
        {
            return false;
        }
    }

    private static bool IsLowerHexSha256(string value)
        => value.Length == 64
            && value.All(static character => character is >= '0' and <= '9'
                or >= 'a' and <= 'f');

    private static string FixedChild(string directory, string leafName)
    {
        string fullDirectory = Path.TrimEndingDirectorySeparator(
            Path.GetFullPath(directory));
        string candidate = Path.GetFullPath(
            Path.Combine(fullDirectory, leafName));
        if (!string.Equals(
                Path.GetDirectoryName(candidate),
                fullDirectory,
                StringComparison.OrdinalIgnoreCase)
            || !string.Equals(
                Path.GetFileName(candidate),
                leafName,
                StringComparison.Ordinal))
        {
            throw new InvalidDataException(
                "The metadata cache path escaped its fixed directory.");
        }

        return candidate;
    }

    private static bool TryResolveManagedTempDirectory(
        string directory,
        out string canonicalDirectory)
    {
        canonicalDirectory = "";
        if (string.IsNullOrWhiteSpace(directory)
            || !Path.IsPathFullyQualified(directory))
        {
            return false;
        }

        string tempRoot = Path.TrimEndingDirectorySeparator(
            Path.GetFullPath(Path.GetTempPath()));
        string fullDirectory = Path.TrimEndingDirectorySeparator(
            Path.GetFullPath(directory));
        string relative = Path.GetRelativePath(tempRoot, fullDirectory);
        bool lexicalInside = !Path.IsPathFullyQualified(relative)
            && relative is not ("." or "..")
            && !relative.StartsWith(
                ".." + Path.DirectorySeparatorChar,
                StringComparison.Ordinal)
            && !relative.StartsWith(
                ".." + Path.AltDirectorySeparatorChar,
                StringComparison.Ordinal);
        if (!lexicalInside)
            return false;

        if (!WindowsPathIdentity.TryResolveExistingDirectory(
                tempRoot,
                out string canonicalTempRoot))
        {
            return false;
        }

        string canonicalPrefix = Path.TrimEndingDirectorySeparator(
                canonicalTempRoot)
            + Path.DirectorySeparatorChar;
        // Existing synthetic directories are bound by their final identity.
        // A missing direct child is also allowed because many WPF smoke
        // fixtures create their handle-validated TEMP root first and let the
        // cache writer create only this derived-cache child later.
        // codeql[cs/path-injection]
        if (Directory.Exists(fullDirectory))
        {
            if (!WindowsPathIdentity.TryResolveExistingDirectory(
                    fullDirectory,
                    out canonicalDirectory))
            {
                return false;
            }
        }
        else
        {
            string? parent = Path.GetDirectoryName(fullDirectory);
            string leaf = Path.GetFileName(fullDirectory);
            if (string.IsNullOrWhiteSpace(parent)
                || string.IsNullOrWhiteSpace(leaf)
                || !Directory.Exists(parent)
                || !WindowsPathIdentity.TryResolveExistingDirectory(
                    parent,
                    out string canonicalParent))
            {
                return false;
            }

            canonicalDirectory = FixedChild(canonicalParent, leaf);
        }

        bool canonicalInside = canonicalDirectory.StartsWith(
            canonicalPrefix,
            StringComparison.OrdinalIgnoreCase);
        if (!canonicalInside)
            canonicalDirectory = "";
        return canonicalInside;
    }
}
